name: build
on:
  workflow_dispatch:
    inputs:
      rabbitmqVer:
        description: RabbitMQ version
        required: true
        type: string
      delayedPlugin:
        description: rabbitmq_delayed_message_exchange version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Replace Version
        run: |
          sed -i 's/RABBITMQ_VER/${rabbitmqVer}/g' Dockerfile
          sed -i 's/DELAYED_PLUGIN/${delayedPlugin}/g' Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thesixonenine/rabbitmq-delayed:${rabbitmqVer}
